# Generated by Django 3.2.4 on 2022-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_consultant',
            field=models.BooleanField(default=False, verbose_name='Consultant Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=False, verbose_name='Patient Status'),
        ),
    ]
