# Generated by Django 3.2.4 on 2022-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='name',
            field=models.CharField(default='doctor', max_length=250),
        ),
    ]
