# Generated by Django 3.2.4 on 2022-04-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consultant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='history',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
