# Generated by Django 3.2.4 on 2022-06-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_patient_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Packs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('benefits', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Subscription Packs',
            },
        ),
    ]
