# Generated by Django 3.2.4 on 2022-06-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscription_packs_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribed_Users',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'Subscribed Users',
            },
        ),
    ]
