# Generated by Django 3.2.4 on 2022-06-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subscribed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribed_users',
            name='subscription_type',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscription_packs'),
        ),
    ]
