# Generated by Django 3.2.4 on 2022-04-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('timeStamp', models.DateTimeField()),
                ('slug', models.CharField(max_length=350)),
                ('tags', models.TextField()),
            ],
        ),
    ]
